### ISSUE TITLE
can't change permision to read and change site data . 

### ISSUE THREAD

**Issue by isahillohiya** [kwame-mintah/bionic-reading-chrome-extension#1]
I am trying to set the permission to "On all sites " but that option is disabled (gray color on option ). and also it is also not changing text to bionic when clicking the extension with the current setting. ( Works in preview)

**Comment by kwame-mintah** [comment]
@isahillohiya - The extension is in the early stages, will attempt to address this issue hopefully today.

**Comment by isahillohiya** [comment]
it's opening a new page but the new page is empty.

**Comment by LordAndy316** [comment]
Resolved
